apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend:20.20.8-13
  labels:
    app: backend:20.20.8-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend:20.20.8-13
  template:
    metadata:
      labels:
        app: backend:20.20.8-13
    spec:
      containers:
      - name: container-backend:20.20.8-13
        image: 34.125.175.151:8083/backend:20.20.8-13
        imagePullSecrets:
      - name: registry-secret
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend:20.20.8-13
  labels:
    app: backend:20.20.8-13
spec:
  ports:
  - port: 8080
  selector:
    app: backend:20.20.8-13